import logging
from abc import ABC, abstractmethod
from typing import Generic, TypeVar, final

import pandas as pd

from ....database.repositories.market_data_provider import MarketDataProvider
from ....mapping import mapper
from ....services.telegram import TelegramBot

logger = logging.getLogger(__name__)

T = TypeVar("T")


class BaseStrategy(ABC, Generic[T]):
    name: str = "Base"

    def __init__(
        self,
        data_provider: MarketDataProvider,
        telegram_bot: TelegramBot | None = None,
    ) -> None:
        """
        Base class for all screening strategies.

        Decoupled from the database — persistence must be defined in subclasses via DI.
        The data provider is injected here; repositories are injected in concrete subclasses.
        """
        self.data_provider = data_provider
        self.telegram_bot = telegram_bot

    @abstractmethod
    def run(self, days: int = 0, analysis_date: str | None = None) -> int:
        """
        Executes the strategy screening pipeline.

        Args:
            days: Lookback offset in calendar days (0 = today / live run).
            analysis_date: ISO date string override for backtesting (YYYY-MM-DD).
                When provided, the strategy must use this date instead of
                deriving it from the current timestamp.

        Returns:
            Number of signals or trade proposals generated by this run.
        """
        raise NotImplementedError

    @final
    def _get_exchange(self, symbol: str) -> str:
        return mapper.get_exchange(symbol, default="UNKNOWN")

    @final
    def _send_telegram_report(self, title: str, date: str, data: pd.DataFrame) -> None:
        if not self.telegram_bot or data.empty:
            return

        full_title = "\U0001f50e {} ({})".format(title, date)
        self.telegram_bot.send_dataframe(data, title=full_title)
