"""Screener candidates and webhook signal inspection tools for Croc-Trader MCP."""

import json
import logging
from typing import Any

from mcp.server import MCPServer

from ...const import Strategies
from ...routes.views.dependencies import (
    _get_screener_view_service,
    _get_signal_repository,
)

logger = logging.getLogger(__name__)


def get_screener_candidates(
    strategy: str | None = None,
    limit: int = 50,
) -> list[dict[str, Any]]:
    """Returns list of screener setup candidates.

    Args:
        strategy: Canonical strategy name (e.g. 'dip_buyer', 'tgim', 'ndx_momentum') or None for all.
        limit: Maximum candidates to return (default 50).
    """
    try:
        view_service = _get_screener_view_service()
        effective_limit = max(1, min(limit, 200))

        if strategy:
            candidates = view_service.get_candidates(strategy, limit=effective_limit)
        else:
            strategies_to_scan = [
                Strategies.DipBuyer,
                Strategies.TurnOverTiming,
                Strategies.TwoPercent,
                Strategies.NDXMomentum,
                Strategies.TGIM,
                Strategies.BridgeScout,
                Strategies.BounceBandit,
                Strategies.HoldTarget,
                Strategies.SplitTarget,
            ]
            candidates = []
            for strat in strategies_to_scan:
                candidates.extend(view_service.get_candidates(strat, limit=20))

        return [dict(c) for c in candidates[:effective_limit]]
    except Exception as error:
        logger.error("Error fetching screener candidates: %s", error)
        return []


def get_turnover_candidates(limit: int = 50) -> list[dict[str, Any]]:
    """Returns list of turnover timing candidates.

    Args:
        limit: Maximum candidates to return (default 50).
    """
    try:
        effective_limit = max(1, min(limit, 200))
        view_service = _get_screener_view_service()
        candidates = view_service.get_turnover_candidates(limit=effective_limit)
        return [dict(c) for c in candidates[:effective_limit]]
    except Exception as error:
        logger.error("Error fetching turnover candidates: %s", error)
        return []


def get_webhook_signals(
    symbol: str | None = None,
    limit: int = 20,
) -> list[dict[str, Any]]:
    """Returns list of incoming webhook signals.

    Args:
        symbol: Optional ticker symbol filter.
        limit: Maximum signals to return (default 20, max 100).
    """
    try:
        effective_limit = max(1, min(limit, 100))
        repo = _get_signal_repository()
        if symbol:
            rows = repo.fetch_all(
                "SELECT * FROM croc WHERE symbol = ? ORDER BY created_at DESC LIMIT ?",
                (symbol.upper().strip(), effective_limit),
            )
        else:
            rows = repo.fetch_all(
                "SELECT * FROM croc ORDER BY created_at DESC LIMIT ?",
                (effective_limit,),
            )
        results = []
        for row in rows:
            sig = dict(row)
            if isinstance(sig.get("data"), str):
                try:
                    sig["data"] = json.loads(str(sig["data"]))
                except (json.JSONDecodeError, TypeError):
                    logger.debug("Signal payload is not valid JSON string.")
            results.append(sig)
        return results
    except Exception as error:
        logger.error("Error fetching webhook signals: %s", error)
        return []


def register(server: MCPServer) -> None:
    """Registers screener and signal inspection tools on the MCP server."""
    server.tool(
        name="get_screener_candidates",
        description=(
            "Fetches setup candidates generated by screening strategies "
            "(e.g. DipBuyer, NDXMomentum, TGIM, BridgeScout, BounceBandit, HoldTarget, SplitTarget)."
        ),
    )(get_screener_candidates)

    server.tool(
        name="get_turnover_candidates",
        description=(
            "Fetches aggregated Turnover Timing candidates ranked by 20-day Average Dollar Volume."
        ),
    )(get_turnover_candidates)

    server.tool(
        name="get_webhook_signals",
        description=(
            "Fetches recently ingested TradingView webhook signals from the signal registry."
        ),
    )(get_webhook_signals)
