"""Characterization and Pinning Tests for TGIM Screener and Trade Manager.

These tests pin the exact baseline behavior of TGIMStrategy across both
Screener and Trade Manager before any refactoring takes place, guaranteeing
100% behavioral equivalence and zero regressive impact.
"""

from decimal import Decimal
from unittest.mock import MagicMock

import pandas as pd
import pytest

from app.const import ExitReason, Strategies
from app.database.repositories.market_data_provider import MarketDataProvider
from app.database.repositories.trade import TradeRepository
from app.services.screener.strategies.tgim import (
    MIN_POSTMARKET_HISTORY_BARS,
    MIN_PREMARKET_HISTORY_BARS,
    TGIMConfiguration,
    evaluate_tgim_setup,
)
from app.services.screener.strategies.tgim import (
    TGIMStrategy as TGIMScreener,
)
from app.services.trade_manager.strategies.tgim import (
    MAX_TGIM_HOLDING_BARS,
    TGIMTradeStrategy,
    calculate_tgim_position_quantity,
    evaluate_tgim_exit,
)

# ==============================================================================
# 1. Attribute Pinning: Verify Canonical Class Attributes
# ==============================================================================


@pytest.mark.tier1
def test_pinning_tgim_default_attributes() -> None:
    """Pins class attributes and strategy identifiers on TGIM Screener and Trade Manager."""
    assert TGIMScreener.STRATEGY_IDENTIFIER == Strategies.TGIM
    assert TGIMScreener.name == Strategies.TGIM
    assert TGIMScreener.TARGET_SYMBOL == "SPY"
    assert TGIMScreener.DEFAULT_MAX_HOLDING_BARS == 2
    assert TGIMScreener.DEFAULT_LOOKBACK_PERIOD == 30
    assert MIN_PREMARKET_HISTORY_BARS == 2
    assert MIN_POSTMARKET_HISTORY_BARS == 3

    assert TGIMTradeStrategy.STRATEGY_IDENTIFIER == Strategies.TGIM
    assert TGIMTradeStrategy.name == Strategies.TGIM
    assert MAX_TGIM_HOLDING_BARS == 2


# ==============================================================================
# 2. Pure Calculation Pinning: Setup Evaluation Logic
# ==============================================================================


@pytest.mark.tier1
def test_pinning_tgim_setup_formula_and_trigger() -> None:
    """Pins Monday Close < min(Friday Close, Thursday Close) setup rule."""
    # Case 1: Triggered (Monday 495 < min(500, 505) = 500)
    res_triggered = evaluate_tgim_setup(
        current_close=Decimal("495.00"),
        friday_close=Decimal("500.00"),
        thursday_close=Decimal("505.00"),
    )
    assert res_triggered.is_signal is True
    assert res_triggered.threshold_price == Decimal("500.00")
    assert res_triggered.setup_close == Decimal("495.00")

    # Case 2: Rejected because Close >= min (Monday 500 == Friday 500)
    res_equal = evaluate_tgim_setup(
        current_close=Decimal("500.00"),
        friday_close=Decimal("500.00"),
        thursday_close=Decimal("505.00"),
    )
    assert res_equal.is_signal is False

    # Case 3: Rejected because Close > min (Monday 502 > Friday 500)
    res_higher = evaluate_tgim_setup(
        current_close=Decimal("502.00"),
        friday_close=Decimal("500.00"),
        thursday_close=Decimal("505.00"),
    )
    assert res_higher.is_signal is False

    # Case 4: Thursday is lower than Friday
    res_thursday_lower = evaluate_tgim_setup(
        current_close=Decimal("485.00"),
        friday_close=Decimal("500.00"),
        thursday_close=Decimal("490.00"),
    )
    assert res_thursday_lower.is_signal is True
    assert res_thursday_lower.threshold_price == Decimal("490.00")


# ==============================================================================
# 3. Screener Proposal Payload Pinning
# ==============================================================================


@pytest.mark.tier1
def test_pinning_tgim_screener_proposal_payload() -> None:
    """Pins exact trade proposal payload generated by TGIM screener."""
    mock_trade_repo = MagicMock(spec=TradeRepository)
    mock_trade_repo.exists.return_value = False
    mock_data_provider = MagicMock(spec=MarketDataProvider)
    df_history = pd.DataFrame(
        [
            {"date": pd.Timestamp("2026-02-05"), "close": 505.0},
            {"date": pd.Timestamp("2026-02-06"), "close": 500.0},
            {"date": pd.Timestamp("2026-02-09"), "close": 495.0},
        ]
    )
    mock_data_provider.get_batch_history.return_value = {"SPY": df_history}

    screener = TGIMScreener(
        trade_repository=mock_trade_repo, data_provider=mock_data_provider
    )

    result = screener.run(analysis_date="2026-02-09")
    assert result == 1

    mock_trade_repo.create_trade.assert_called_once_with(
        symbol="SPY",
        strategy=Strategies.TGIM,
        size=0.0,
        entry=500.0,
        stop_loss=0.0,
        target=0.0,
        context={
            "date": "2026-02-09",
            "setup_date": "2026-02-09",
            "setup_close": 495.0,
            "threshold_price": 500.0,
            "friday_close": 500.0,
            "thursday_close": 505.0,
            "day": "Monday",
            "max_holding_bars": 2,
            "source": "ScreenerEngine",
        },
    )


# ==============================================================================
# 4. Position Sizing Pinning: Floor Quantity Calculation
# ==============================================================================


@pytest.mark.tier1
def test_pinning_tgim_position_quantity() -> None:
    """Pins strict floor rounding for TGIM position sizing."""
    assert calculate_tgim_position_quantity(Decimal("10000.0"), Decimal("500.0")) == 20
    # 10000 / 499 = 20.04008 -> 20 shares
    assert calculate_tgim_position_quantity(Decimal("10000.0"), Decimal("499.0")) == 20
    # 10000 / 501 = 19.96 -> 19 shares
    assert calculate_tgim_position_quantity(Decimal("10000.0"), Decimal("501.0")) == 19
    # Edge conditions
    assert calculate_tgim_position_quantity(Decimal("0.0"), Decimal("500.0")) == 0
    assert calculate_tgim_position_quantity(Decimal("10000.0"), Decimal("0.0")) == 0
    assert calculate_tgim_position_quantity(Decimal("-100.0"), Decimal("500.0")) == 0


# ==============================================================================
# 5. Trade Manager Exit Evaluation Pinning: Bar 1 Take Profit vs Bar 2 Time Stop
# ==============================================================================


@pytest.mark.tier1
def test_pinning_tgim_exit_logic_pure() -> None:
    """Pins pure exit evaluation: Bar 0 inactive, Bar 1 TP if Close > Close[1], Bar 2 TP or TE."""
    # Bar 0 (Monday): Inactive
    assert (
        evaluate_tgim_exit(
            bars_held=0,
            current_close=Decimal("510.0"),
            previous_close=Decimal("500.0"),
        )
        is None
    )

    # Bar 1 (Tuesday): Take Profit if Close > Prev Close
    assert (
        evaluate_tgim_exit(
            bars_held=1,
            current_close=Decimal("501.0"),
            previous_close=Decimal("500.0"),
        )
        == ExitReason.TAKE_PROFIT
    )
    # Bar 1 (Tuesday): Hold if Close <= Prev Close
    assert (
        evaluate_tgim_exit(
            bars_held=1,
            current_close=Decimal("499.0"),
            previous_close=Decimal("500.0"),
        )
        is None
    )
    assert (
        evaluate_tgim_exit(
            bars_held=1,
            current_close=Decimal("500.0"),
            previous_close=Decimal("500.0"),
        )
        is None
    )

    # Bar 2 (Wednesday): Take Profit if Close > Prev Close
    assert (
        evaluate_tgim_exit(
            bars_held=2,
            current_close=Decimal("501.0"),
            previous_close=Decimal("500.0"),
        )
        == ExitReason.TAKE_PROFIT
    )
    # Bar 2 (Wednesday): Time Stop if Close <= Prev Close
    assert (
        evaluate_tgim_exit(
            bars_held=2,
            current_close=Decimal("499.0"),
            previous_close=Decimal("500.0"),
        )
        == ExitReason.TIME_STOP
    )
    assert (
        evaluate_tgim_exit(
            bars_held=2,
            current_close=Decimal("500.0"),
            previous_close=Decimal("500.0"),
        )
        == ExitReason.TIME_STOP
    )


# ==============================================================================
# 6. Dependency Injection Pinning: Custom Configuration Override
# ==============================================================================


@pytest.mark.tier1
def test_pinning_tgim_screener_custom_configuration() -> None:
    """Pins ability to customize parameters via TGIMConfiguration injection."""
    custom_cfg = TGIMConfiguration(
        target_symbol="QQQ",
        lookback_period=45,
        min_premarket_history_bars=1,
    )
    mock_trade_repo = MagicMock(spec=TradeRepository)
    mock_trade_repo.exists.return_value = False
    mock_data_provider = MagicMock(spec=MarketDataProvider)
    df_history = pd.DataFrame(
        [
            {"date": pd.Timestamp("2026-02-05"), "close": 505.0},
            {"date": pd.Timestamp("2026-02-06"), "close": 500.0},
            {"date": pd.Timestamp("2026-02-09"), "close": 490.0},
        ]
    )
    mock_data_provider.get_batch_history.return_value = {"QQQ": df_history}

    screener = TGIMScreener(
        trade_repository=mock_trade_repo,
        data_provider=mock_data_provider,
        configuration=custom_cfg,
    )

    assert screener.configuration.target_symbol == "QQQ"
    assert screener.configuration.lookback_period == 45
    assert screener.configuration.min_premarket_history_bars == 1

    result = screener.run(analysis_date="2026-02-09")
    assert result == 1

    mock_trade_repo.create_trade.assert_called_once()
    assert mock_trade_repo.create_trade.call_args.kwargs["symbol"] == "QQQ"


@pytest.mark.tier1
def test_pinning_tgim_trade_manager_custom_configuration() -> None:
    """Pins ability to customize max holding bars via TGIMConfiguration injection."""
    custom_cfg = TGIMConfiguration(max_holding_bars=3)
    trade_manager = TGIMTradeStrategy(configuration=custom_cfg)

    assert trade_manager.configuration.max_holding_bars == 3

    # At bar 2 (Wednesday), with max_holding_bars=3, holding is not yet exhausted
    assert (
        evaluate_tgim_exit(
            bars_held=2,
            current_close=Decimal("495.0"),
            previous_close=Decimal("500.0"),
            max_holding_bars=trade_manager.configuration.max_holding_bars,
        )
        is None
    )

    # At bar 3 (Thursday), holding is exhausted -> Time Stop
    assert (
        evaluate_tgim_exit(
            bars_held=3,
            current_close=Decimal("495.0"),
            previous_close=Decimal("500.0"),
            max_holding_bars=trade_manager.configuration.max_holding_bars,
        )
        == ExitReason.TIME_STOP
    )
